name: Test and Deploy workflow

on:
  push:
    branches:
      - master

jobs:
  sonar:
    name: SonarQube Anlysis
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder - SonarQube
        run: |
          echo "SonarQube check passed"
          echo "✅ SonarQube completed at $(date)" | tee -a audit-log-sonar.log

      - name: Upload Audit log
        uses: actions/upload-artifact@v4
        with:
          name: audit-log-sonar
          path: audit-log-sonar.log

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          echo "✅ Dependencies installed at $(date)" | tee -a audit-log-lint.log

      - name: Run Linter
        run: |
          flake8 . | tee -a audit.log
          echo "✅ Linting completed at $(date)" | tee -a audit-log-lint.log

      - name: Upload Audit log
        uses: actions/upload-artifact@v4
        with:
          name: audit-log-lint
          path: audit-log-lint.log

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [sonar, lint]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Step
        run: echo "Deployment Successfull"

  consolidate-logs:
    name: Consolidate logs
    runs-on: ubuntu-latest
    needs: [sonar, lint]
    steps:
      - name: Download all logs
        uses: actions/download-artifact@v4

      - name: Merge logs
        run: |
          cat audit-log-sonar/audit-log-sonar.log >> audit-logs.log
          cat audit-log-lint/audit-log-lint.log >> audit-logs.log
          echo "✅ All logs consolidate at $(date)" >> audit-logs.log

      - name: Upload Consolidate Audit log
        uses: actions/upload-artifact@v4
        with:
          name: audit-logs
          path: audit-logs.log

  send-email:
    name: Send Email Notification
    runs-on: ubuntu-latest
    needs: consolidate-logs
    steps:
      - name: Prompt for email input
        id: get_email
        run: |
          echo "Enter recipient email address:"
          read email
          echo "EMAIL=$email" >> $GITHUB_ENV

      - name: Download Consolidate Audit Log
        uses: actions/download-artifact@v4
        with:
          name: audit-logs
          path: .

      - name: Simulate Email Sending
        run: |
          echo "📧 Simulating email sending ...."
          echo "To: ${{ env.EMAIL }}"
          echo "From: GitHub Actions <hello@poolcamacho.dev>"
