name: Test and Deploy workflow

on:
  push:
    branches:
      - master

jobs:
  sonar:
    name: SonarQube Anlysis
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder - SonarQube
        run: echo "SonarQube check passed"
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8
      
      - name: Run Linter
        run: flake8 .
      
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [sonar, lint]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Step
        run: echo "Deployment Successfull"

  